=== systerel/S2OPC/schemas/s2opc_clientserver_config.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="S2OPC" type="S2OPCType"/>
  <xs:simpleType name="SecurityURI">
    <xs:restriction base="xs:anyURI">
      <xs:enumeration value="http://opcfoundation.org/UA/SecurityPolicy#None"/>
      <xs:enumeration value="http://opcfoundation.org/UA/SecurityPolicy#Basic256"/>
      <xs:enumeration value="http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256"/>
      <xs:enumeration value="http://opcfoundation.org/UA/SecurityPolicy#Aes128_Sha256_RsaOaep"/>
      <xs:enumeration value="http://opcfoundation.org/UA/SecurityPolicy#Aes256_Sha256_RsaPss"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="SecurityMode">
    <xs:restriction base="xs:string">
      <xs:enumeration value="None"/>
      <xs:enumeration value="Sign"/>
      <xs:enumeration value="SignAndEncrypt"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="TokenType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="anonymous"/>
      <xs:enumeration value="username"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="NamespaceType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:anyURI" name="uri" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="NamespacesType">
    <xs:sequence>
      <xs:element type="NamespaceType" name="Namespace" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="LocaleType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="id" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="LocalesType">
    <xs:sequence>
      <xs:element type="LocaleType" name="Locale" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ServerCertificateType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="path" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="ServerKeyType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="path" use="required"/>
        <xs:attribute type="xs:string" name="encrypt" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="IssuerType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="cert_path" use="required"/>
        <xs:attribute type="xs:string" name="revocation_list_path" use="required"/>
        <xs:attribute type="xs:boolean" name="root" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="TrustedIssuersType">
    <xs:sequence>
      <xs:element type="IssuerType" name="TrustedIssuer" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>One or several trusted certificate authorities</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="IssuedCertificateType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="path" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="IssuedCertificatesType">
    <xs:sequence>
      <xs:element type="IssuedCertificateType" name="IssuedCertificate" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>One or several explicitly trusted certificates issued by provided issuers or self-signed</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="UntrustedIssuersType">
    <xs:sequence>
      <xs:element type="IssuerType" name="UntrustedIssuer" maxOccurs="unbounded">
        <xs:annotation>
          <xs:documentation>One or several untrusted certificate authorities. Those are only used to validate trust chain of issued certificate.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ApplicationCertificatesType">
    <xs:sequence>
      <xs:element type="ServerCertificateType" name="ServerCertificate" />
      <xs:element type="ServerKeyType" name="ServerKey" />
      <xs:element type="TrustedIssuersType" name="TrustedIssuers" minOccurs="0"/>
      <xs:element type="IssuedCertificatesType" name="IssuedCertificates" minOccurs="0">
        <xs:annotation>
          <xs:documentation>At least one shall be filled in either TrustedIssuers or IssuedCertificates</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element type="UntrustedIssuersType" name="UntrustedIssuers" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ApplicationURIType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:anyURI" name="uri" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="ProductURIType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:anyURI" name="uri" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="ApplicationNameType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="text" use="required"/>
        <xs:attribute type="xs:string" name="locale" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="ApplicationDescriptionType">
    <xs:sequence>
      <xs:element type="ApplicationURIType" name="ApplicationURI" />
      <xs:element type="ProductURIType" name="ProductURI" />
      <xs:element type="ApplicationNameType" name="ApplicationName" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="SecurityModeType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="SecurityMode" name="mode" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="SecurityModesType">
    <xs:sequence>
      <xs:element type="SecurityModeType" name="SecurityMode" maxOccurs="3" minOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="SecurityPolicyType">
    <xs:sequence>
      <xs:element type="SecurityModesType" name="SecurityModes"/>
      <xs:element name="UserPolicies">
        <xs:complexType mixed="true">
          <xs:sequence>
            <xs:element type="UserPolicyType" name="UserPolicy" maxOccurs="5">
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute type="SecurityURI" name="uri" use="required"/>
  </xs:complexType>
  <xs:complexType name="UserPolicyType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="policyId"  use="required"/>
        <xs:attribute type="TokenType" name="tokenType"  use="required">
          <xs:annotation>
            <xs:documentation>Available token types are only anonymous and username. Security URI available is only None</xs:documentation>
          </xs:annotation>
        </xs:attribute>
        <xs:attribute type="SecurityURI" name="securityUri" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="UserPoliciesType">
    <xs:sequence>
      <xs:element type="UserPolicyType" name="UserPolicy" maxOccurs="5" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Available token types are only anonymous and username. Security URI available is only None</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="SecurityPoliciesType">
    <xs:sequence>
      <xs:element type="SecurityPolicyType" name="SecurityPolicy" maxOccurs="5" minOccurs="1">
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ReverseConnectionType">
    <xs:attribute type="xs:anyURI" name="clientUrl" use="required"/>
    <xs:attribute type="xs:anyURI" name="clientAppUri" use="optional"/>
  </xs:complexType>
  <xs:complexType name="ReverseConnectionsType">
    <xs:sequence>
      <xs:element type="ReverseConnectionType" name="ReverseConnection" maxOccurs="unbounded" minOccurs="0">
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="EndpointType">
    <xs:sequence>
      <xs:element type="ReverseConnectionsType" name="ReverseConnections" minOccurs="0"/>
      <xs:element type="SecurityPoliciesType" name="SecurityPolicies"/>
    </xs:sequence>
    <xs:attribute type="xs:anyURI" name="url" use="required"/>
    <xs:attribute type="xs:boolean" name="hasDiscoveryEndpoint" use="optional" default="true">
        <xs:annotation>
          <xs:documentation>By default each endpoint has an implicit discovery endpoint if security mode None is not available. Set to 'false' to deactivate.</xs:documentation>
        </xs:annotation>
    </xs:attribute>
    <xs:attribute type="xs:boolean" name="enableListening" use="optional" default="true">
        <xs:annotation>
          <xs:documentation>This attribute might be set to false to avoid listening for client connections only if at least one ReverseConnection is defined.</xs:documentation>
        </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  <xs:complexType name="EndpointsType">
    <xs:sequence>
      <xs:element type="EndpointType" name="Endpoint" maxOccurs="254">
        <xs:annotation>
          <xs:documentation>Note: Endpoint no transport URI (only TCP available) and no security level (computed by server)</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ServerConfigurationType">
    <xs:sequence>
      <xs:element type="NamespacesType" name="Namespaces" />
      <xs:element type="LocalesType" name="Locales" />
      <xs:element type="ApplicationCertificatesType" name="ApplicationCertificates" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Certificates not necessary if only security policy None is used</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element type="ApplicationDescriptionType" name="ApplicationDescription" />
      <xs:element type="EndpointsType" name="Endpoints" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="S2OPCType">
    <xs:sequence>
      <xs:element type="ServerConfigurationType" name="ServerConfiguration" />
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== systerel/S2OPC/tests/ClientServer/data/config/S2OPC_Test_XML_Config.xml
<?xml version='1.0' encoding='utf-8'?>
<S2OPC xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="s2opc_clientserver_config.xsd">
  <ServerConfiguration>
    <Namespaces>
      <Namespace uri="urn:S2OPC:MY_SERVER_HOST"/>
      <Namespace uri="urn:S2OPC:MY_SERVER_HOST:2"/>
    </Namespaces>
    <Locales>
      <Locale id="en"/>
      <Locale id="es-ES"/>
      <Locale id="fr-FR"/>
    </Locales>
    <ApplicationCertificates>
      <ServerCertificate path="/mypath/mycert.der"/>
      <ServerKey path="/mypath/mykey.pem"/>
      <TrustedIssuers>
        <TrustedIssuer root="true" cert_path="/mypath/cacert.der" revocation_list_path="/mypath/cacrl.der"/>
        <TrustedIssuer root="true" cert_path="/mypath/othercacert.der" revocation_list_path="/mypath/othercacrl.der"/>
        <TrustedIssuer root="false" cert_path="/mypath/intermediate_cacert.der" revocation_list_path="/mypath/intermediate_cacrl.der"/>
      </TrustedIssuers>
      <IssuedCertificates>
        <IssuedCertificate path="/mypath/self_signed.der"/>
        <IssuedCertificate path="/mypath/signed_by_not_trusted_ca.der"/>
      </IssuedCertificates>
      <UntrustedIssuers>
        <UntrustedIssuer root="true" cert_path="/mypath/not_trusted_ca.der" revocation_list_path="/mypath/not_trusted_revoked.crl"/>
        <UntrustedIssuer root="false" cert_path="/mypath/not_trusted_intermediate_ca.der" revocation_list_path="/mypath/not_trusted_intermediate_revoked.crl"/>
      </UntrustedIssuers>
    </ApplicationCertificates>
    <ApplicationDescription>
      <ApplicationURI uri="urn:S2OPC:MY_SERVER_HOST:app"/>
      <ProductURI uri="urn:S2OPC:MY_SERVER_HOST:prod"/>
      <ApplicationName text="S2OPC toolkit configuration example" locale="en"/>
      <ApplicationName text="S2OPC toolkit: ejemplo de configuraciÃ³n" locale="es-ES"/>
      <ApplicationName text="S2OPC toolkit: exemple de configuration" locale="fr-FR"/>
      <!-- No discovery URL: we only support current endpoint URL as discovery URL for now -->
    </ApplicationDescription>
    <Endpoints>
      <!-- Note: Endpoint no transport URI (only TCP available) and no security level (computed by server) -->
      <Endpoint url="opc.tcp://MY_SERVER_HOST:4841/MY_ENPOINT_NAME" enableListening="false">
        <ReverseConnections>
          <ReverseConnection clientUrl="opc.tcp://localhost:4842"/>
          <ReverseConnection clientAppUri="urn:S2OPC:client" clientUrl="opc.tcp://localhost:4843"/>
        </ReverseConnections>
        <SecurityPolicies>
          <!-- Only None/Basic256/Basic256Sha256 available -->
          <SecurityPolicy uri="http://opcfoundation.org/UA/SecurityPolicy#None">
            <SecurityModes>
              <SecurityMode mode="None"/>
            </SecurityModes>
            <UserPolicies>
              <UserPolicy policyId="anon" tokenType="anonymous"/>
            </UserPolicies>
          </SecurityPolicy>
          <SecurityPolicy uri="http://opcfoundation.org/UA/SecurityPolicy#Basic256">
            <SecurityModes>
              <SecurityMode mode="Sign"/>
            </SecurityModes>
            <UserPolicies>
              <UserPolicy policyId="anon1" tokenType="anonymous"/>
            </UserPolicies>
          </SecurityPolicy>
          <SecurityPolicy uri="http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256">
            <SecurityModes>
              <SecurityMode mode="Sign"/>
              <SecurityMode mode="SignAndEncrypt"/>
            </SecurityModes>
            <UserPolicies>
              <!-- Available token types are only anonymous and username. Security URI available is only None -->
              <UserPolicy policyId="anon2" tokenType="anonymous"/>
              <UserPolicy policyId="user1" tokenType="username" securityUri="http://opcfoundation.org/UA/SecurityPolicy#None"/>
            </UserPolicies>
          </SecurityPolicy>
          <SecurityPolicy uri="http://opcfoundation.org/UA/SecurityPolicy#Aes128_Sha256_RsaOaep">
            <SecurityModes>
              <SecurityMode mode="Sign"/>
              <SecurityMode mode="SignAndEncrypt"/>
            </SecurityModes>
            <UserPolicies>
              <!-- Available token types are only anonymous and username. Security URI available is only None -->
              <UserPolicy policyId="anon2" tokenType="anonymous"/>
              <UserPolicy policyId="user1" tokenType="username" securityUri="http://opcfoundation.org/UA/SecurityPolicy#None"/>
            </UserPolicies>
          </SecurityPolicy>
          <SecurityPolicy uri="http://opcfoundation.org/UA/SecurityPolicy#Aes256_Sha256_RsaPss">
            <SecurityModes>
              <SecurityMode mode="Sign"/>
              <SecurityMode mode="SignAndEncrypt"/>
            </SecurityModes>
            <UserPolicies>
              <!-- Available token types are only anonymous and username. Security URI available is only None -->
              <UserPolicy policyId="anon2" tokenType="anonymous"/>
              <UserPolicy policyId="user1" tokenType="username" securityUri="http://opcfoundation.org/UA/SecurityPolicy#None"/>
            </UserPolicies>
          </SecurityPolicy>
        </SecurityPolicies>
      </Endpoint>
      <Endpoint url="opc.tcp://MY_SERVER_HOST:4841/MY_ENPOINT_NAME_2">
        <ReverseConnections/>
        <SecurityPolicies>
          <SecurityPolicy uri="http://opcfoundation.org/UA/SecurityPolicy#None">
            <SecurityModes>
              <SecurityMode mode="None"/>
            </SecurityModes>
            <UserPolicies>
              <UserPolicy policyId="anon" tokenType="anonymous"/>
            </UserPolicies>
          </SecurityPolicy>
          <SecurityPolicy uri="http://opcfoundation.org/UA/SecurityPolicy#Basic256">
            <SecurityModes>
              <SecurityMode mode="SignAndEncrypt"/>
            </SecurityModes>
            <UserPolicies>
              <!-- Available token types are only anonymous and username. Security URI available is only None -->
              <UserPolicy policyId="username" tokenType="username" securityUri="http://opcfoundation.org/UA/SecurityPolicy#None"/>/>
            </UserPolicies>
          </SecurityPolicy>
        </SecurityPolicies>
      </Endpoint>
    </Endpoints>
  </ServerConfiguration>
</S2OPC>

=== systerel/S2OPC/tests/ClientServer/data/config/S2OPC_Server_Test_Faulty_Packet_Config.xml
<?xml version='1.0' encoding='utf-8'?>
<S2OPC xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="s2opc_clientserver_config.xsd">
  <ServerConfiguration>
    <Locales>
      <Locale id="en-US"/>
      <Locale id="fr-FR"/>
    </Locales>
    <ApplicationDescription>
      <ApplicationURI uri="urn:S2OPC:localhost"/>
      <ProductURI uri="urn:S2OPC:localhost:product"/>
      <ApplicationName text="S2OPC toolkit server example" locale="en-US"/>
      <ApplicationName text="S2OPC toolkit: exemple de serveur" locale="fr-FR"/>
      <ApplicationType type="DiscoveryServer"/>
    </ApplicationDescription>
    <Endpoints>
      <Endpoint url="opc.tcp://localhost:4841">
        <SecurityPolicies>
          <SecurityPolicy uri="http://opcfoundation.org/UA/SecurityPolicy#None">
            <SecurityModes>
                <SecurityMode mode="None"/>
            </SecurityModes>
            <UserPolicies>
                <UserPolicy policyId="anon" tokenType="anonymous"/>
            </UserPolicies>
          </SecurityPolicy>
        </SecurityPolicies>
      </Endpoint>
    </Endpoints>
  </ServerConfiguration>
</S2OPC>

=== systerel/S2OPC/samples/ClientServer/data/config/S2OPC_Server_CSPN_ST_Config.xml
<?xml version='1.0' encoding='utf-8'?>
<S2OPC xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="s2opc_clientserver_config.xsd">
  <ServerConfiguration>
    <Locales>
      <Locale id="en-US"/>
      <Locale id="fr-FR"/>
    </Locales>
    <ApplicationCertificates>
      <ServerCertificate path="server_public/server_4k_cert.der"/>
      <ServerKey path="server_private/encrypted_server_4k_key.pem" encrypted="true"/>
      <ServerPublicKeyInfrastructure path="./S2OPC_Demo_PKI"/>
    </ApplicationCertificates>
    <ApplicationDescription>
      <ApplicationURI uri="urn:S2OPC:localhost"/>
      <ProductURI uri="urn:S2OPC:localhost:product"/>
      <ApplicationName text="S2OPC toolkit server security target example" locale="en-US"/>
      <ApplicationName text="S2OPC toolkit: exemple de cible de sécurité serveur" locale="fr-FR"/>
      <!-- No discovery URL: use of endpoint URL as discovery URL -->
    </ApplicationDescription>
    <Endpoints>
      <Endpoint url="opc.tcp://localhost:4841">
        <SecurityPolicies>
          <SecurityPolicy uri="http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256">
            <SecurityModes>
              <SecurityMode mode="Sign"/>
              <SecurityMode mode="SignAndEncrypt"/>
            </SecurityModes>
            <UserPolicies>
              <UserPolicy policyId="user" tokenType="username" securityUri="http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256"/>
            </UserPolicies>
          </SecurityPolicy>
        </SecurityPolicies>
      </Endpoint>
    </Endpoints>
  </ServerConfiguration>
</S2OPC>
