=== systerel/S2OPC/schemas/s2opc_pubsub_config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
     <xs:element name="PubSub">
           <xs:complexType>
                 <xs:sequence>
                       <xs:element name="connection" maxOccurs="unbounded">
                             <xs:complexType>
                                   <xs:sequence>
                                         <xs:element name="message" maxOccurs="unbounded">
                                               <xs:complexType>
                                                     <xs:sequence>
                                                           <xs:element name="variable" maxOccurs="unbounded">
                                                                 <xs:complexType>
                                                                       <xs:attribute name="nodeId" type="xs:string" use="required"/>
                                                                       <xs:attribute name="displayName" type="xs:string" use="required"/>
                                                                       <xs:attribute name="dataType" type="dataType" use="required"/>
                                                                 </xs:complexType>
                                                           </xs:element>
                                                     </xs:sequence>
                                                     <xs:attribute name="id" type="xs:unsignedInt" use="required"/>
                                                     <xs:attribute name="publishingInterval" type="xs:double" use="required"/>
                                                     <xs:attribute name="version" type="xs:unsignedInt" use="required"/>
                                                     <xs:attribute name="publisherId" type="xs:unsignedLong"/> <!-- required if subscriber mode -->
                                               </xs:complexType>
                                         </xs:element>
                                   </xs:sequence>
                                   <xs:attribute name="address" type="xs:string" use="required"/>
                                   <xs:attribute name="mode" type="modeType" use="required"/>
                             </xs:complexType>
                       </xs:element>
                 </xs:sequence>
                 <xs:attribute name="publisherId" type="xs:unsignedLong"/> <!-- required if publisher connection defined -->
           </xs:complexType>
     </xs:element>
     <xs:simpleType name="modeType">
       <xs:restriction base="xs:string">
         <xs:enumeration value="publisher"/>
         <xs:enumeration value="subscriber"/>
       </xs:restriction>
     </xs:simpleType>
     <xs:simpleType name="dataType">
       <xs:restriction base="xs:string">
         <xs:enumeration value="Null"/>
         <xs:enumeration value="Boolean"/>
         <xs:enumeration value="SByte"/>
         <xs:enumeration value="Byte"/>
         <xs:enumeration value="Int16"/>
         <xs:enumeration value="UInt16"/>
         <xs:enumeration value="Int32"/>
         <xs:enumeration value="UInt32"/>
         <xs:enumeration value="Int64"/>
         <xs:enumeration value="UInt64"/>
         <xs:enumeration value="Float"/>
         <xs:enumeration value="Double"/>
         <xs:enumeration value="DateTime"/>
         <xs:enumeration value="String"/>
         <xs:enumeration value="ByteString"/>
         <xs:enumeration value="Guid"/>
         <xs:enumeration value="XmlElement"/>
         <xs:enumeration value="NodeId"/>
         <xs:enumeration value="ExpandedNodeId"/>
         <xs:enumeration value="QualifiedName"/>
         <xs:enumeration value="LocalizedText"/>
         <xs:enumeration value="StatusCode"/>
         <xs:enumeration value="Structure"/>
       </xs:restriction>
     </xs:simpleType>
 </xs:schema>

=== systerel/S2OPC/samples/PubSub/data/config_zephyr_perf.xml
<PubSub publisherId="42" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="s2opc_pubsub_config.xsd">
    <connection address="opc.udp://232.1.2.101:4840" mode="publisher">
        <message id="21" version="1" publishingInterval="1000" securityMode="none">
            <variable nodeId="ns=1;s=PubVarResult" dataType="Byte" displayName="ignored"/>
            <variable nodeId="ns=1;s=PubVarInfo" dataType="String" displayName="ignored"/>
            <variable nodeId="ns=1;s=PubVarLoops" dataType="UInt32" displayName="ignored"/>
            <variable nodeId="ns=1;s=PubVarUpTime" dataType="UInt32" displayName="ignored"/>
        </message>
    </connection>
    <!-- The emitter subscribes to the variable that has been looped-back,
         but stores it in another cell of the cache -->
    <connection address="opc.udp://232.1.2.100:4840" mode="subscriber">
        <message id="20" version="1" publishingInterval="1" securityMode="none" publisherId="42">
            <variable nodeId="ns=1;s=SubVarLoops" dataType="UInt32" displayName="ignored"/>
            <variable nodeId="ns=1;s=SubPeriodMs" dataType="UInt32" displayName="ignored"/>
            <variable nodeId="ns=1;s=Spare64" dataType="UInt64" displayName="ignored"/>
        </message>
    </connection>
</PubSub>

=== systerel/S2OPC/samples/platform_specific/freertos/PubSub/config_publisher_mqtt_test_py/config_publisher_mqtt_test_py.xml
<PubSub xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="s2opc_pubsub_config.xsd">
    <connection address="mqtts://192.168.1.64:1883" publisherId="42" mode="publisher" mqttUsername="user1" mqttPassword="password" >
        <message groupId="14" groupVersion="1" publishingInterval="1000." mqttTopic="S2OPC" >
          <dataset>
            <variable nodeId="ns=1;s=PubUInt" displayName="varUInt" dataType="Unt32"/>
            <variable nodeId="ns=2;i=6" displayName="PubFloat" dataType="Float"/>
          </dataset>
        </message>
        <message groupId="15" groupVersion="1" publishingInterval="2000." >
          <dataset>
            <variable nodeId="ns=1;s=PubInt" displayName="varInt" dataType="Int32"/>
            <variable nodeId="ns=1;s=PubUInt" displayName="varUInt" dataType="UInt32"/>
          </dataset>
        </message>
    </connection>
</PubSub>

=== systerel/S2OPC/samples/platform_specific/freertos/PubSub/config_publisher_test_format_JSON/config_publisher_test_format_JSON.xml
<PubSub xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="s2opc_pubsub_config.xsd">
    <connection address="mqtts://192.168.1.108:1883" publisherId="42" mode="publisher" mqttUsername="user1" mqttPassword="password" >
        <message groupId="14" groupVersion="1" publishingInterval="1000." mqttTopic="S2OPC" >
          <dataset>
            <variable nodeId="ns=1;s=PubBool" displayName="PubBool" dataType="Boolean"/>
            <variable nodeId="ns=1;s=PubInt64" displayName="varInt" dataType="Int64"/>
            <variable nodeId="ns=1;s=PubUInt64" displayName="varInt" dataType="UInt64"/>
            <variable nodeId="ns=1;s=PubInt32" displayName="varInt" dataType="Int32"/>
            <variable nodeId="ns=1;s=PubUInt32" displayName="PubFloat" dataType="UInt32"/>
            <variable nodeId="ns=1;s=PubInt16" displayName="varInt" dataType="Int16"/>
            <variable nodeId="ns=1;s=PubUInt16" displayName="PubFloat" dataType="UInt16"/>
            <variable nodeId="ns=2;i=6" displayName="PubFloat" dataType="Float"/>
            <variable nodeId="ns=1;s=PubDouble" displayName="varDouble" dataType="Double"/>
            <variable nodeId="ns=1;s=PubString" displayName="PubFloat" dataType="String"/>
          </dataset>
        </message>
    </connection>
</PubSub>

=== systerel/S2OPC/samples/PubSub_ClientServer/data/config/config_sub_server.xml
<PubSub publisherId="42" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="s2opc_pubsub_config.xsd">
    <connection address="opc.eth://01-00-00-01-04-00" mode="subscriber" interfaceName="test_veth">
        <message id="14" version="1" publishingInterval="100." publisherId="42" securityMode="signAndEncrypt">
            <variable nodeId="ns=1;s=SubBool" displayName="varBool" dataType="Boolean"/>
            <variable nodeId="ns=1;s=SubString" displayName="varString" dataType="String"/>
        </message>
        <message id="15" version="1" publishingInterval="1000." publisherId="42">
            <variable nodeId="ns=1;s=SubInt" displayName="varInt" dataType="Int64"/>
            <variable nodeId="ns=1;s=SubUInt" displayName="varUInt" dataType="UInt64"/>
        </message>
    </connection>
</PubSub>

=== systerel/S2OPC/samples/platform_specific/freertos/PubSub/config_publisher_sensors/config_publisher_sensors.xml
<PubSub xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="s2opc_pubsub_config.xsd">
    <connection address="mqtts://a23slny5qs4w87-ats.iot.eu-west-3.amazonaws.com:8883" publisherId="42" mode="publisher" mqttUsername="user1" mqttPassword="password" >
        <message groupId="14" groupVersion="1" publishingInterval="1000." mqttTopic="S2OPC" >
          <dataset>
            <variable nodeId="ns=2;i=0" displayName="Temperature0" dataType="Float"/>
            <variable nodeId="ns=2;i=1" displayName="Temperature1" dataType="Float"/>
            <variable nodeId="ns=2;i=2" displayName="Humidity" dataType="Float"/>
            <variable nodeId="ns=2;i=3" displayName="Pressure" dataType="Float"/>
            <variable nodeId="ns=2;i=4" displayName="AcceleroX" dataType="Int32"/>
            <variable nodeId="ns=2;i=5" displayName="AcceleroY" dataType="Int32"/>
            <variable nodeId="ns=2;i=6" displayName="AcceleroZ" dataType="Int32"/>
          </dataset>
        </message>
    </connection>
</PubSub>
